#!/bin/bash

. profile

execute() {
cd $1
. ./profile
. ./core
run
}

while true; do
    for plugin in ${plugins[@]}; do
        CURR=$(pwd)
        execute plugins/$plugin
        cd $CURR
    done
    sleep $delay
done
